// Generated by scripts/gen_params.py. Do not hand edit constants.
package params_pkg;
  parameter int N = 4096;
  parameter int LOGN = 12;
  parameter int QW = 64;
  parameter int PATH = 2;
  parameter int MUL_LAT = 3;

  localparam logic [QW-1:0] Q         = 64'h0fffffffffffc001;
  localparam logic [QW-1:0] QINV      = 64'h0efffbffefffbfff;
  localparam logic [QW-1:0] R_MOD_Q   = 64'h000000000003fff0;
  localparam logic [QW-1:0] R2_MOD_Q  = 64'h0000000fff800100;
  localparam logic [QW-1:0] N_INV     = 64'h0ffeffffffffc005;
  localparam logic [QW-1:0] N_INV_MONT= 64'h0010000000000000;
  localparam logic [QW-1:0] PSI       = 64'h05fd601f95c9428a;
  localparam logic [QW-1:0] OMEGA     = 64'h08f0f412d0d11f35;

  typedef enum logic [1:0] {
    MODE_NTT  = 2'b01,
    MODE_INTT = 2'b10
  } ntt_mode_t;
endpackage
