#!/usr/bin/env python3
"""Generate the common 60-bit NTT and Montgomery constants."""

from pathlib import Path

N = 4096
LOGN = 12
QW = 64
R = 1 << QW


def is_prime(n: int) -> bool:
    if n < 2:
        return False
    for p in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37):
        if n % p == 0:
            return n == p
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    for a in (2, 325, 9375, 28178, 450775, 9780504, 1795265022):
        if a % n == 0:
            continue
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(s - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def find_parameters() -> dict[str, int]:
    k = ((1 << 60) - 1) // (2 * N)
    while True:
        q = k * (2 * N) + 1
        if is_prime(q):
            break
        k -= 1

    psi = next(
        pow(g, (q - 1) // (2 * N), q)
        for g in range(2, 10000)
        if pow(g, (q - 1) // 2, q) == q - 1
    )
    return {
        "Q": q,
        "QINV": (-pow(q, -1, R)) % R,
        "R_MOD_Q": R % q,
        "R2_MOD_Q": (R * R) % q,
        "N_INV": pow(N, -1, q),
        "N_INV_MONT": (pow(N, -1, q) * R) % q,
        "PSI": psi,
        "OMEGA": pow(psi, 2, q),
    }


def main() -> None:
    p = find_parameters()
    text = f"""// Generated by scripts/gen_params.py. Do not hand edit constants.
package params_pkg;
  parameter int N = {N};
  parameter int LOGN = {LOGN};
  parameter int QW = {QW};
  parameter int PATH = 2;
  parameter int MUL_LAT = 3;

  localparam logic [QW-1:0] Q         = 64'h{p["Q"]:016x};
  localparam logic [QW-1:0] QINV      = 64'h{p["QINV"]:016x};
  localparam logic [QW-1:0] R_MOD_Q   = 64'h{p["R_MOD_Q"]:016x};
  localparam logic [QW-1:0] R2_MOD_Q  = 64'h{p["R2_MOD_Q"]:016x};
  localparam logic [QW-1:0] N_INV     = 64'h{p["N_INV"]:016x};
  localparam logic [QW-1:0] N_INV_MONT= 64'h{p["N_INV_MONT"]:016x};
  localparam logic [QW-1:0] PSI       = 64'h{p["PSI"]:016x};
  localparam logic [QW-1:0] OMEGA     = 64'h{p["OMEGA"]:016x};

  typedef enum logic [1:0] {{
    MODE_NTT  = 2'b01,
    MODE_INTT = 2'b10
  }} ntt_mode_t;
endpackage
"""
    out = Path(__file__).resolve().parents[1] / "rtl" / "params_pkg.sv"
    out.write_text(text, encoding="ascii")
    for name, value in p.items():
        print(f"{name:8s} = {value} (0x{value:016x})")


if __name__ == "__main__":
    main()
